version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      npm-production:
        dependency-type: production
      npm-development:
        dependency-type: development
    labels: [dependencies]
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels: [dependencies, github-actions]
    open-pull-requests-limit: 5
